name: flutter_tree_sitter_python
description: "A Flutter FFI plugin for tree-sitter-python"
version: 0.0.1
homepage: https://github.com/qiuxiang/flutter-tree-sitter-python

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tree_sitter: ^0.0.1

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

ffigen:
  output: "lib/src/bindings.g.dart"
  headers:
    entry-points:
      - "./src/tree_sitter_python.c"
  exclude-all-by-default: true
  functions:
    include:
      - tree_sitter_python
  enums:
    include:
      - "ts_.*"
